In [2]:
import numpy as np
import pandas as pd

In [8]:
## Create numpy array
array_1d = np.array([1,2,3])
array_2d = np.array([[1,2,3],[4,5,6]])
print array_1d
print array_2d
array_2d[0,1]

[1 2 3]
[[1 2 3]
 [4 5 6]]


2

In [30]:
## Create pandas series
series = pd.Series({"time":1,"data":2,"Name":"Mu"})
series1 = pd.Series([1,2,"Mu"],index=["time",'data','name'])
print series1, type(series1)
print series
## Creat pandas datafram
#DF = pd.DataFrame({"time":1,"data":2,"Name":"Mu"},{"time":5,"data":8,"Name":"Xin"}) # This is not right
#DF1 = pd.DataFrame({"time":1,"data":2,"Name":"Mu"})## This is not right
DF1 = pd.DataFrame({"time":[1],"data":[2],"Name":["Mu"]})
print DF1
DF = pd.DataFrame({"time":[1,8],"data":[2,6],"Name":["Mu",'Xin']},index=["#1",'#2']) # This is right, this is the same as R
print DF

time     1
data     2
name    Mu
dtype: object <class 'pandas.core.series.Series'>
Name    Mu
data     2
time     1
dtype: object
  Name  data  time
0   Mu     2     1
   Name  data  time
#1   Mu     2     1
#2  Xin     6     8


In [9]:
## Using pandas to read a file saved as a datafram
df = pd.read_table("C:/Users/Xin/Desktop/Github-repo/Independent_Data_Science_Projects/Linear_Regression/Python/Data.txt",header= None,sep='  ')
##two space as sep

C:\Users\Xin\Anaconda3\envs\ipykernel_py2\lib\site-packages\ipykernel\__main__.py:2: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  from ipykernel import kernelapp as app


In [10]:
df

0    1
0    80  399
1    30  121
2    50  221
3    90  376
4    70  361
5    60  224
6   120  546
7    80  352
8   100  353
9    50  157
10   40  160
11   70  252
12   90  389
13   20  113
14  110  435
15  100  420
16   30  212
17   50  268
18   90  377
19  110  421
20   30  273
21   90  468
22   40  244
23   80  342
24   70  323

In [13]:
df1 = pd.read_csv("C:/Users/Xin/Desktop/Github-repo/Independent_Data_Science_Projects/Linear_Regression/Python/Data.txt",header= None,sep="  ")

C:\Users\Xin\Anaconda3\envs\ipykernel_py2\lib\site-packages\ipykernel\__main__.py:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  if __name__ == '__main__':


In [14]:
df1

0    1
0    80  399
1    30  121
2    50  221
3    90  376
4    70  361
5    60  224
6   120  546
7    80  352
8   100  353
9    50  157
10   40  160
11   70  252
12   90  389
13   20  113
14  110  435
15  100  420
16   30  212
17   50  268
18   90  377
19  110  421
20   30  273
21   90  468
22   40  244
23   80  342
24   70  323

In [15]:
df2 = pd.read_csv("C:/Users/Xin/Desktop/Github-repo/Independent_Data_Science_Projects/Linear_Regression/Python/Data_csv.txt",header= None)

In [24]:
df2

0    1
0    80  399
1    30  121
2    50  221
3    90  376
4    70  361
5    60  224
6   120  546
7    80  352
8   100  353
9    50  157
10   40  160
11   70  252
12   90  389
13   20  113
14  110  435
15  100  420
16   30  212
17   50  268
18   90  377
19  110  421
20   30  273
21   90  468
22   40  244
23   80  342
24   70  323

In [22]:
## Using numpy to read the data in as matrix
mat = np.loadtxt("C:/Users/Xin/Desktop/Github-repo/Independent_Data_Science_Projects/Linear_Regression/Python/Data.txt")

In [23]:
mat

array([[  80.,  399.],
       [  30.,  121.],
       [  50.,  221.],
       [  90.,  376.],
       [  70.,  361.],
       [  60.,  224.],
       [ 120.,  546.],
       [  80.,  352.],
       [ 100.,  353.],
       [  50.,  157.],
       [  40.,  160.],
       [  70.,  252.],
       [  90.,  389.],
       [  20.,  113.],
       [ 110.,  435.],
       [ 100.,  420.],
       [  30.,  212.],
       [  50.,  268.],
       [  90.,  377.],
       [ 110.,  421.],
       [  30.,  273.],
       [  90.,  468.],
       [  40.,  244.],
       [  80.,  342.],
       [  70.,  323.]])

In [26]:
type(mat)

numpy.ndarray